---
language: python
python: "2.7"
dist: trusty

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/

env:
  - ANSIBLE_VERSION=1.9.6
  - ANSIBLE_VERSION=2.0.2.0
  - ANSIBLE_VERSION=2.1.4.0
  - ANSIBLE_VERSION=2.2.1.0

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine

install:
  - pip install tox-travis

script:
  - tox
