---

- name: Check if debian testing is enabled
  command: grep -qr "debian/ testing main" /etc/apt
  register: prosody_debian_testing
  check_mode: False
  changed_when: False
  failed_when: False
  when: prosody_libevent is undefined

- set_fact:
    prosody_libevent: True
  when: prosody_libevent is undefined and
    (ansible_distribution_major_version|int > 9 or
    (ansible_distribution_major_version|int == 9 and prosody_debian_testing.rc == 0))

- include: prosody.yml
  tags:
    - prosody

- include: monitoring.yml
  when: prosody_monitoring
  tags:
    - prosody
    - molecule_test_skip

- include: inactive.yml
  tags:
    - prosody

- include: ldap.yml
  when: prosody_authentication == "cyrus"
  tags:
    - prosody
    - ldap

- include: web.yml
  when: prosody_web_dir|default(False) and prosody_web_user|default(False)
  tags:
    - web
