- include: prosody.yml
  tags:
    - prosody

- include: monitoring.yml
  when: prosody_monitoring
  tags:
    - prosody

- include: inactive.yml
  tags:
    - prosody

- include: ldap.yml
  when: prosody_authentication == "cyrus"
  tags:
    - prosody
    - ldap
