---
scenario:
  name: default

driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: stretch64
    box: debian/stretch64
    memory: 512
    cpus: 2
    # provider_raw_config_args:
    # - "customize [ 'modifyvm', :id, '--uartmode1', 'disconnected' ]"

provisioner:
  name: ansible
  become: true
  lint:
    name: ansible-lint
    enabled: false

lint:
  name: yamllint
  options:
    config-data:
      extends: default
      rules:
        line-length:
          max: 120
verifier:
  name: goss
  lint:
    name: yamllint
