---
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: prosody-buster64
    box: debian/buster64
lint: |
  set -e
  yamllint .
  ansible-lint
provisioner:
  name: ansible
  become: true
verifier:
  name: goss
